#!/bin/bash

alias anacon='export PATH="/home/smartin/anaconda2/bin:$PATH"'
alias l="ls --color=auto -alh"
alias dush="du -sh *"
alias attach="screen -Adr"
alias ack="ack-grep"

# these load the ssh key as needed rather than ever damn time 
# i log the fuck in. see also: ssh-agent
ssh() {
  if ! ssh-add -l >/dev/null 2>&-; then
    ssh-add ~/.ssh/id_rsa
  fi
  /usr/bin/ssh "$@"
}
export -f ssh

git() {
  if ! ssh-add -l >/dev/null 2>&-; then
    ssh-add ~/.ssh/id_rsa
  fi
  /usr/bin/git "$@"
}
export -f git

sr() {
  if [ "$1" == "" ]; then
    echo "Usage: sr <host> <ssh opts>"
    return 1
  fi
  host="$1"
  shift
  ssh root@$host $@
}

burner() {
  docker run -it --rm -v $(pwd):/pwd $@
}

bgburner() {
  n=$RANDOM
  docker run -d --name bgburner-$n $@
  echo "container running: bgburner-$n"
}

alias el7pass="python -c 'import crypt,getpass; print(crypt.crypt(getpass.getpass(), crypt.mksalt(crypt.METHOD_SHA512)))'"

pycompile() {
  python -m py_compile $@
}

pynotebook() {
  if [ "$1" != "" ]; then
    d="$1"
  else
    d="$(pwd)"
  fi
  docker run --rm -it -p 8888:8888 -v "${d}":/home/jovyan/work/"$(basename $d)" -e PASSWORD=pornmuffins jupyter/minimal-notebook
}
